Add vip-block-data-api in vip-integrations folder
Automattic/vip-go-mu-plugins-ext pull request #30
Opened 2023-04-24 07:48 UTC by alecgeatches

Include [vip-block-data-api](https://github.com/Automattic/vip-block-data-api) configuration to be pulled into the `vip-integrations/` folder. I've tested that locally the `folderPrefix` works well with a subfolder as defined in the configuration.

Including plugins in a subfolder has the main advantage that it can help to declutter `vip-go-mu-plugins` - optional integration plugins are not exposed as must-use plugins unless explicitly loaded.

2023-04-24 08:13 UTC, pschoffer requested changes, later dismissed
Looks great! Could you please also add the README section about why we have added `vip-blocks-data-api` here?

2023-04-24 09:35 UTC, alecgeatches commented
@pschoffer Thank you for looking it over! Added a blurb in the README with some context. Let me know if you're looking for something different.

2023-04-26 15:51 UTC, rinatkhaziev approved these changes

2023-04-27 03:36 UTC, merged

2023-04-27 03:40 UTC, alecgeatches commented
@rinatkhaziev @pschoffer Thank you! I've merged and verified `vip-block-data-api` was successfully pulled into `vip-integrations`: https://github.com/Automattic/vip-go-mu-plugins-ext/tree/trunk/vip-integrations/.